import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import ReactQuerySetup from "./ReactQuerySetup";
import Head from "next/head";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Passportt Authentication",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script async src="https://js.stripe.com/v3/pricing-table.js" />

      <body className="bg-zinc-100">
        <NextTopLoader color="#22c55e" />
        <ReactQuerySetup>{children}</ReactQuerySetup>
      </body>
    </html>
  );
}
